services:
    app:
        build: .
        container_name: "audio-parser"
        restart: unless-stopped
        volumes:
            - sockets:/run/sockets
        networks:
            - socket-link

    server:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - sockets:/run/sockets
        networks:
            - socket-link
        depends_on:
            - app
        ports:
            - ${PORT}:8080

volumes:
    sockets:
networks:
    socket-link:



