# Generated by Django 5.0.7 on 2024-07-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cents', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ratio_enumerator', models.IntegerField()),
                ('ratio_denominator', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intervals', models.ManyToManyField(to='pitches.interval')),
            ],
        ),
    ]
