# Generated by Django 5.0.7 on 2024-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='ratio_denominator',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='interval',
            name='ratio_enumerator',
            field=models.IntegerField(blank=True),
        ),
    ]
