# Generated by Django 5.0.7 on 2024-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interval",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intervalname",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scale",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="system",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
