# Generated by Django 5.0.7 on 2024-07-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0003_alter_interval_ratio_denominator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interval',
            old_name='ratio_enumerator',
            new_name='ratio_numerator',
        ),
    ]
