#!/bin/bash

#Cents calculation: n = 1200 × log₂(f₂ / f₁)
#bc uses ln, so divide by l(2) to get binary log

#Output cents difference between P1 and P2
printf "%.2f\n" $(bc -l <<< "l(${2}/${1})/l(2) * 1200")
